export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const REGISTER_USER = 'REGISTER_USER';

export const REQUEST_VERIFICATION_CODE = 'REQUEST_VERIFICATION_CODE';
export const CODE_VERIFICATION = 'CODE_VERIFICATION';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
